import InputError from '../../components/authentication/InputError'
import AuthSessionStatus from '../../components/authentication/AuthSessionStatus'
import Head from 'next/head'
import ProductsHeroSecion from '../../components/products/products-hero-section'
import { useAuth } from '../../hooks/auth'
import { useEffect,useState } from 'react'
import { useRouter } from 'next/router'

const PasswordReset = () => {
    const router = useRouter()

    const { resetPassword } = useAuth({ middleware: 'guest' })

    const [email, setEmail] = useState('')
    const [password, setPassword] = useState('')
    const [passwordConfirmation, setPasswordConfirmation] = useState('')
    const [errors, setErrors] = useState([])
    const [status, setStatus] = useState(null)

    const submitForm = event => {
        event.preventDefault()

        resetPassword({
            email,
            password,
            password_confirmation: passwordConfirmation,
            setErrors,
            setStatus,
        })
    }

    useEffect(() => {
        setEmail(router.query.email || '')
    }, [router.query.email])

    return (
    <div>
        <Head>
          <title>Rest Password</title>
          <meta title="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <ProductsHeroSecion image="/accountbg.jpg"/>
        <div dir='rtl' className="h-full lg:w-1/2 w-full px-8 py-6 mt-4"style={{"margin-top": "-100px"}}>
            <h3 className="text-right text-2xl font-Roboto font-bold">أدخل كلمة سر جديدة</h3>
            {/* Session Status */}
            <AuthSessionStatus className="mb-4" status={status} />

            <form className="mt-4 p-4 border border-gray-200" onSubmit={submitForm}>
                <div>
                    <label className="font-Roboto block" for="email"> البريد الإلكتروني *</label>
                    <input type="text"value={email} id="email"
                        className="w-full px-4 py-2 mt-2 border rounded-md focus:outline-none 
                        focus:ring-1 focus:ring-orange-700"
                        onChange={event => setEmail(event.target.value)}/>
                    <InputError messages={errors.email} className="mt-2" />
                </div>
                <div className="mt-4">
                    <label className="font-Roboto block">كلمة المرور *</label>
                    <input type="password"value={password} id="password"
                        className="w-full px-4 py-2 mt-2 border rounded-md focus:outline-none 
                        focus:ring-1 focus:ring-orange-700"
                        onChange={event => setPassword(event.target.value)}/>
                        <InputError messages={errors.password}className="mt-2"/>
                </div>
                <div className="mt-4">
                    <label className="font-Roboto block">كلمة المرور تثبيت*</label>
                    <input type="password"value={passwordConfirmation} id="passwordConfirmation"
                        className="w-full px-4 py-2 mt-2 border rounded-md focus:outline-none 
                        focus:ring-1 focus:ring-orange-700"
                        onChange={event =>
                            setPasswordConfirmation(event.target.value)
                        }/>
                        <InputError messages={errors.password_confirmation}className="mt-2"/>
                </div>
                <div className="flex items-center justify-end mt-4">
                    <button className="px-6 py-2 mt-4 text-white bg-orange-500 rounded-lg hover:bg-orange-700">غيّر كلمة السر</button>
                </div>
            </form>
        </div>
    </div>
    )
}

export default PasswordReset
