import axios from '../../lib/axios';
import { useState } from 'react';

import Head from 'next/head'
import Header from '../../components/layout/main-header'
import Footer from '../../components/layout/footer'
import ProductsHeroSecion from '../../components/products/products-hero-section'
import LangSwitch from '../../components/layout/langswitch'

import Product from '../../components/products/product';
import ProductsFilters from '../../components/products/products-filters'
import Branches from '../../components/branches'
import ProductsCategoriesNav from '../../components/products/products-categories-nav'
import TypesNav from '../../components/types/types-nav'

function FilterProductsPage(props) {
  const categories = props.allcategories;
  const types = props.alltypes;
  // const products = props.allproducts;  
  const sortedproducts = sortData(data);  

  return (
      <div>
      <Head>
      <title>{category.name}</title>
        <meta title="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LangSwitch />
      <Header />
      <ProductsHeroSecion />

      <ProductsCategoriesNav categories={categories}/>
         
      <div className='mx-6'>
      <ProductsFilters/>
      <div className="my-10 bg-white border border-black shadow-xl px-6 py-4 relative z-1 w-3/4 h-auto mx-auto rounded-lg">
      <TypesNav types={types}/>
      <Product products={sortedproducts} />
      </div>
      </div>      
      <Branches/>
      <Footer />
      </div>
    )
  }
  export async function getStaticProps(context) {
    const categories = await axios.get("http://127.0.0.1:8000/api/categories");
    const types = await axios.get("http://127.0.0.1:8000/api/types");
    const products = await axios.get("http://127.0.0.1:8000/api/products");

    return {
      props: {
        allcategories: categories.data,
        alltypes: types.data,
        allproducts: products.data,
      },
      revalidate: 30
    };
  }
  // using data from parameter instead of state
//   export async function getSortedData(sortPrice) {
//   const { price } = sortPrice;

//   const res = await fetch("http://127.0.0.1:8000/api/products");
//   const allproducts = await res.json()

//   let sortedData;
//   if (sortPrice === 'descending') {
//     sortedData = [...allproducts].sort((a, b) => {
//       return b.price - a.price;
//     });
//     console.log("high to low")
//     console.log(sortedData)
//   } else if (sortPrice === 'ascending') {
//     sortedData = [...allproducts].sort((a, b) => {
//       return a.price - b.price;
//     });
//     console.log("low to high")
//     console.log(sortedData) 
//   } else {
//     return data;
//   }
//     return sortedData;
// }
export default FilterProductsPage;