import axios from '../../lib/axios';

import Head from 'next/head'
import Header from '../../components/layout/main-header'
import Footer from '../../components/layout/footer'
import ProductsHeroSecion from '../../components/products/products-hero-section'
import LangSwitch from '../../components/layout/langswitch'

import Products from '../../components/products/products';
import Branches from '../../components/branches'
import ProductsCategoriesNav from '../../components/products/products-categories-nav'

export default function ProductsPage(props) {
  const category = props.selectedCategory; 
  const categories = props.allcategories;
    return (
      <div>
      <Head>
        <title>{category.name}</title>
        <meta title="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LangSwitch />
      <Header />
      <ProductsHeroSecion />

      <ProductsCategoriesNav categories={categories}/>
         
      <Products categoryId={category.id} />
      <Branches/>
      <Footer />
      </div>
    )
  }
  export async function getStaticProps(context) {
    const categories = await axios.get("http://127.0.0.1:8000/api/categories");

    const categoryId = context.params.categoryid;
    
    const category = await axios.get(`http://127.0.0.1:8000/api/categories/${categoryId}`);
    return {
      props: {
        allcategories: categories.data,
        selectedCategory: category.data
      },
      revalidate: 30
    };
  }
  
  export async function getStaticPaths() {
    const categories =  await axios.get("http://127.0.0.1:8000/api/categories");
    const pathsWithParams =  categories.data.map((category) => ({
      params: { categoryid: category.id.toString()},
    }))
  
    return {
      paths: pathsWithParams,
      fallback: false
    };
  }
 