import dynamic from 'next/dynamic';
import axios from '../lib/axios';

import Head from 'next/head'
// import HeroSection from '../components/hero-section'
// import CategoriesSection from '../components/categories-section'
import Branches from '../components/branches'

const HeroSection = dynamic(() => import('../components/hero-section'), {
  loading: () => 'Loading...',
})
const CategoriesSection = dynamic(() => import('../components/categories-section'), {
  loading: () => 'Loading...',
})
export default function Home(props) {
  const { categories } = props;
  return (
    <div>
      <Head>
        <title>Km Almajdal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroSection />
      <CategoriesSection categories={categories}/>
      <Branches/>
    </div>
  )
}

export async function getStaticProps()
{
 const response = await axios.get("http://127.0.0.1:8000/api/categories");
 return {
     props: {
         categories: response.data
     },
 }
}