import { useAuth } from '../hooks/auth'
import { useEffect, useState } from 'react'
import { useRouter } from 'next/router'
import Head from 'next/head'
import Footer from '../components/layout/footer'
import ProductsHeroSecion from '../components/products/products-hero-section'

import InputError from '../components/authentication/InputError'
function Login() {
    const router = useRouter()

    const { login } = useAuth({
        middleware: 'guest',
        redirectIfAuthenticated: '/dashboard',
    })

    const [email, setEmail] = useState('')
    const [password, setPassword] = useState('')
    const [shouldRemember, setShouldRemember] = useState(false)
    const [errors, setErrors] = useState([])
    const [status, setStatus] = useState(null)

    useEffect(() => {
        if (router.query.reset?.length > 0 && errors.length === 0) {
            setStatus(atob(router.query.reset))
        } else {
            setStatus(null)
        }
    })

    const submitForm = async event => {
        event.preventDefault()

        login({
            email,
            password,
            remember: shouldRemember,
            setErrors,
            setStatus,
        })
    }
    return (
        <div>
        <Head>
          <title>Login</title>
          <meta title="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <ProductsHeroSecion image="/accountbg.jpg"/>
        <div dir='rtl' className="h-full lg:w-1/2 w-full px-8 py-6 mt-4"style={{"margin-top": "-100px"}}>
            <h3 className="text-right text-2xl font-Roboto font-bold">تسجيل الدخول</h3>
            <form className="mt-4 p-4 border border-gray-200" onSubmit={submitForm}>
                <div>
                    <div>
                        <label className="font-Roboto block" for="email">اسم المستخدم أو البريد الإلكتروني *</label>
                        <input type="text"value={email} id="email"
                            className="w-full px-4 py-2 mt-2 border rounded-md focus:outline-none 
                            focus:ring-1 focus:ring-orange-700"
                            onChange={event => setEmail(event.target.value)}/>
                    <InputError messages={errors.email} className="mt-2" />
                    </div>
                    <div className="mt-4">
                        <label className="font-Roboto block">كلمة المرور *</label>
                        <input type="password"value={password} id="password"
                            className="w-full px-4 py-2 mt-2 border rounded-md focus:outline-none 
                            focus:ring-1 focus:ring-orange-700"
                            onChange={event => setPassword(event.target.value)}/>
                    <InputError messages={errors.password} className="mt-2" />            
                    </div>
                    <div className="flex items-center mt-4">
                        <input id="default-checkbox" type="checkbox" value="" className="w-4 h-4 text-white bg-orange-500 border-gray-300 
                        focus:ring-orange-700 focus:ring-2"
                        onChange={event =>
                            setShouldRemember(event.target.checked)
                        }/>
                       &nbsp;<label for="default-checkbox" className="ml-2 text-sm font-medium">تذكرني</label>
                    </div>
                        <button className="px-6 py-2 mt-4 text-white bg-orange-500 rounded-lg hover:bg-orange-700">تسجيل الدخول</button>
                        &nbsp;<a href="#" className="text-sm text-orange-500 hover:underline">نسيت كلمة مرورك؟</a>
                </div>
            </form>
        </div>
        <Footer />
        </div>

  );
}

export default Login;