
import Head from 'next/head'
import Header from '../components/layout/main-header'
import Footer from '../components/layout/footer'
import ProductsHeroSecion from '../components/products/products-hero-section'
import LangSwitch from '../components/layout/langswitch'
import AuthForms from '../components/authentication/auth-forms';


export default function MyAccountPage() {
  
    return (
      <div>
      <Head>
        <title>My Account</title>
        <meta title="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LangSwitch />
      <Header />
      <ProductsHeroSecion image="/accountbg.jpg"/>
      <AuthForms/>
      <Footer />
      </div>
    )
  }
 