import { useAuth } from '../hooks/auth'
import { useState } from 'react'
import Head from 'next/head'
import Header from '../components/layout/main-header'
import Footer from '../components/layout/footer'
import ProductsHeroSecion from '../components/products/products-hero-section'
import LangSwitch from '../components/layout/langswitch'

import InputError from '../components/authentication/InputError'
function Register() {
    const { register } = useAuth({
        middleware: 'guest',
        redirectIfAuthenticated: '/dashboard',
    })
    const [phone, setPhone] = useState('')
    const [company, setCompany] = useState('')
    const [name, setName] = useState('')
    const [email, setEmail] = useState('')
    const [password, setPassword] = useState('')
    const [passwordConfirmation, setPasswordConfirmation] = useState('')
    const [errors, setErrors] = useState([])
    
    const submitForm = event => {
        event.preventDefault()
    console.log("hiii")
        register({
            name,
            company,
            phone,
            email,
            password,
            password_confirmation: passwordConfirmation,
            setErrors,
        })
    }
    return (
        <div>
        <Head>
          <title>Register</title>
          <meta title="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <LangSwitch />
        <Header />
        <ProductsHeroSecion image="/accountbg.jpg"/>
        <div dir='rtl' className="h-full lg:w-1/2 w-full px-8 py-6 mt-4"style={{"margin-top": "-100px"}}>
            <h3 className="text-right text-2xl font-Roboto font-bold">تسجيل جديد للشركات و الأفراد</h3>
            <form className="mt-4 p-4 border border-gray-200" onSubmit={submitForm}>
                <div>                
                    <div>
                        <label className="font-Roboto block" for="username">اسم المستخدم *</label>
                        <input type="text"value={name} id="name"
                            className="w-full px-4 py-2 mt-2 border rounded-md focus:outline-none 
                            focus:ring-1 focus:ring-orange-700"
                            onChange={event => setName(event.target.value)}/>
                    </div>                
                    <div className="mt-4">
                        <label className="font-Roboto block" for="company">اسم الشركة *</label>
                        <input type="text"value={company} id="company"
                            className="w-full px-4 py-2 mt-2 border rounded-md focus:outline-none 
                            focus:ring-1 focus:ring-orange-700"
                            onChange={event => setCompany(event.target.value)}/>
                    </div>                
                    <div className="mt-4">
                        <label className="font-Roboto block" for="phone">الهاتف*</label>
                        <input type="text"value={phone} id="phone"
                            className="w-full px-4 py-2 mt-2 border rounded-md focus:outline-none 
                            focus:ring-1 focus:ring-orange-700"
                            onChange={event => setPhone(event.target.value)}/>
                    </div>               
                    <div className="mt-4">
                        <label className="font-Roboto block" for="email">البريد الإلكتروني *</label>
                        <input type="email"value={email} id="email"
                            className="w-full px-4 py-2 mt-2 border rounded-md focus:outline-none 
                            focus:ring-1 focus:ring-orange-700"
                            onChange={event => setEmail(event.target.value)}/>
                            <InputError messages={errors.email} className="mt-2" />
                    </div>
                    <div className="mt-4">
                        <label className="font-Roboto block">كلمة المرور *</label>
                        <input type="password"value={password} id="password"
                            className="w-full px-4 py-2 mt-2 border rounded-md focus:outline-none 
                            focus:ring-1 focus:ring-orange-700"
                            onChange={event => setPassword(event.target.value)}/>
                            <InputError messages={errors.password}className="mt-2"/>
                    </div>
                    <div className="mt-4">
                        <label className="font-Roboto block">كلمة المرور تثبيت*</label>
                        <input type="password"value={passwordConfirmation} id="passwordConfirmation"
                            className="w-full px-4 py-2 mt-2 border rounded-md focus:outline-none 
                            focus:ring-1 focus:ring-orange-700"
                            onChange={event =>
                                setPasswordConfirmation(event.target.value)
                            }/>
                            <InputError messages={errors.password_confirmation}className="mt-2"/>
                    </div>
                    <p className="font-Roboto mt-4">Your personal data will be used to support your experience throughout this website, to manage access to your account, and for other purposes described in our
                    <span className="text-sm text-orange-500 hover:underline">سياسة الخصوصية.</span></p>
                    <button className="px-6 py-2 mt-4 text-white bg-orange-500 rounded-lg hover:bg-orange-700">تسجيل جديد للشركات و الأفراد</button>
                </div>
            </form>
        </div>
        <Footer />
        </div>
    );
  }
  
  export default Register;